### ISSUE TITLE
PIVlab_commandline issues 

### ISSUE THREAD

**Issue by quynhneo** [Shrediquette/PIVlab#14]
https://github.com/Shrediquette/PIVlab/blob/main/PIVlab_commandline.m is not ready to run, for example https://github.com/Shrediquette/PIVlab/blob/main/PIVlab_commandline.m#L16 has `s=cell(11,2)` but should be `s=cell(13,2)` since version 2.01 , or it doesn't save the results, etc. Anyway I have modified the script to make it standalone program, with parallel processing options (which was critical because I had a TB of images to process). If pull requests are welcome, I will submit one.

**Comment by Shrediquette** [comment]
Hi, this shouldn't cause a real issue, because the cell array will be resized when new elements are assigned. But I agree that it is bad coding and should be fixed.
I am happy to receive pull requests. But do I need the parallel processing toolbox for it to work? I don't have it, so I can't check the functionality.

**Comment by quynhneo** [comment]
yes, it looks like there is a free trail version https://www.mathworks.com/products/parallel-computing.html

**Comment by Shrediquette** [comment]
But then I can only test it once and if it is broken with a change in some function, I can never test it again :( There is no solution without an additional toolbox?

**Comment by quynhneo** [comment]
Not that I know of... This sucks, your software is making matlab better and more popular but they are not making it easy for you. Is there no special privilege that comes with being a popular contributor? Can you ask them for a free license?

**Comment by Shrediquette** [comment]
Hi, no they will not help me. Once, I was asking for an extension of the trial period, because mathworks implemented a huge change that broke pivlab completely. As far as I remember, my request was ignored.
I would like to keep the required toolboxes at minimum in PIVlab. The image processing toolbox bis ok in my point of view, because I guess 98% of all MATLAB installations will also have this toolbox.

**Comment by quynhneo** [comment]
parallel processing could be made optional, and put in a try catch block, so no one without the toolbox would accidentally run it.
